host: "0.0.0.0"
port: 8317

auth-dir: "/root/.cli-proxy-api"

api-keys:
  - "sk-cliproxy-default-key-123"

routing:
  strategy: "round-robin"

# Mở quản lý từ xa để truy cập Dashboard qua domain
remote-management:
  allow-remote: true
  secret-key: "admin123"

debug: false
logging-to-file: true
usage-statistics-enabled: true
